### ISSUE TITLE
Add twitter integration to display recent tweets in footer

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#11]

**Comment by mokolabs** [comment]
Okay, I got this working, but it's a bit tricky to style and format.

Here's how it looks when showing three tweets:

<img width="1263" alt="screen shot 2017-03-26 at 6 25 10 pm" src="https://cloud.githubusercontent.com/assets/444/24337407/94fdc092-1251-11e7-8b1e-5b91c63f1065.png">

And here's how it looks with just two tweets (with one photo tweet):

<img width="1263" alt="screen shot 2017-03-26 at 6 16 01 pm" src="https://cloud.githubusercontent.com/assets/444/24337413/a4571764-1251-11e7-90ab-a176e87c7a7d.png">

Do you see what's wrong here?

Each tweet takes up vertical space. So the more tweets you have, the higher the footer height will be. And it's not really predictable because tweets can be short or quite long (especially with photos). So that could look a bit weird -- because we want the tweets to roughly match the height of the other things in the footer.

So, at first, I thought maybe we should just go with one tweet:

<img width="1265" alt="screen shot 2017-03-26 at 6 16 16 pm" src="https://cloud.githubusercontent.com/assets/444/24337417/c2c92fe8-1251-11e7-8620-286a281ffeea.png">

But then I figured out that we can just set a fixed height (and width) for the tweets, and then users can scroll within the tweets to see as much as they want. 

<img width="1261" alt="screen shot 2017-03-26 at 6 34 06 pm" src="https://cloud.githubusercontent.com/assets/444/24337540/262704d8-1253-11e7-90a5-dfdb5d955b1e.png">

... and we're scrolling ...

<img width="1264" alt="screen shot 2017-03-26 at 6 37 05 pm" src="https://cloud.githubusercontent.com/assets/444/24337547/4224c364-1253-11e7-80f5-2e23a6fb6487.png">


I'm currently thinking this is probably the best solution, so I'll go ahead and commit. Check it out and let me know what you think.

Also, here are the docs for doing this: https://dev.twitter.com/web/embedded-timelines

One more thing... because the tweets are loaded via an iframe, we will have no ability to style them. We'll have to stick with the standard look that Twitter uses for tweets (which is fine, I think).

**Comment by mokolabs** [comment]
One more thing... there's an option to show a header and to show borders between tweets, so I enabled those. 

Here's how it looks right now:

<img width="1262" alt="screen shot 2017-03-26 at 6 48 46 pm" src="https://cloud.githubusercontent.com/assets/444/24337747/de6333b8-1254-11e7-8a3b-b5b09c680d55.png">

**Comment by stephchin** [comment]
Looks good!!
