### ISSUE TITLE
Add photo slideshow

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#17]
We should have a section for pictures from prior events whether that's a carousel or image gallery --depends on the look we're going for.

**Comment by mokolabs** [comment]
Let's do a slideshow. We can build on the code we used for the sponsors slideshow.

**Comment by mokolabs** [comment]
I will bug Lisa about getting us some images!

**Comment by mokolabs** [comment]
Okay, Lisa got me some images and I added the slideshow!

The slideshow replaces the #header image. It's the same size as before and is also responsive, but now, instead of a single image, there are five different images. They rotate every 4 seconds, just like the slideshow.

Note: I didn't use lazy loading for these because it would look weird if they popped in the way that the sponsor logos do. When the sponsor logos pop in, it looks intentional. But I don't think that would be the case if we did it with photos.

I also wrote a crazy jQuery function which makes sure that the header images scale correctly as the viewport shrinks and grows. You can try commenting out that function to see what happens without it and why we needed to add that code.

Anyway, check it out. I think it looks pretty cool.

Oh, and hey, I think we're feature-complete now! So great work, guys!

(I'll be adding a few more issues for responsive support, so we make sure the site looks great on smaller screens. Beyond that, we just need to do a deploy soon, and I'll probably tackle that this weekend.)
