### ISSUE TITLE
Add sponsor logos

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#35]

**Comment by mokolabs** [comment]
Good work, @sslampa.

I'm simplifying the sponsor image paths and file names:

**Before:**

```ruby
= link_to image_tag("../assets/sponsor_logos/amazon_logo_CMYK-01.png", class: "img-responsive"), "https://www.amazon.com", target: "_blank"`
```

**After:**

```ruby
= link_to image_tag("/assets/sponsors/amazon.png", class: "img-responsive"), "https://www.amazon.com", target: "_blank"
```

It's a good idea to use root relative paths for images. DEFINITELY don't try using purely relative paths. They will most likely break at some point.

Also, since we're never going to have other kinds of sponsor images, we can rename `sponsor_logos` to just `sponsors` -- it's shorter and easier to type.

The same goes from the individual sponsor images. Stick with a simple, lowercase word for each sponsor. `amazon.png`, `procore.png`, etc.

**Comment by mokolabs** [comment]
Okay, I made a bunch of tweaks to this. Check it out!

**Comment by stephchin** [comment]
I'm gonna be honest I don't love the sponsors section. It feels messy to me, but I can get over it if you feel strongly about displaying it like that.

If not I was thinking maybe we could do something like the triangle site, but have it cycle in brands based on levels (and give higher levels more show time).

![screen shot 2017-03-29 at 9 56 38 am](https://cloud.githubusercontent.com/assets/20118615/24466601/4c6f971c-1466-11e7-9bdc-a2b2d6b472ed.png)

**Comment by mokolabs** [comment]
So harsh! Geez! 😜

To be honest, I don't think sponsor sections are ever amazing looking. Because the logos always have different styles, they inherently clash and can look a bit tacky when they're all on a page together.

![giphy](https://cloud.githubusercontent.com/assets/444/24469684/26aaf124-1471-11e7-92c6-317469adc931.gif)

I do agree, though, that the sponsors block on the triangle site is more attractive in theory. However, it's also way too washed out. Yes, when you hover over a specific sponsor logo, it brightens up and you can see how it normally looks. But, in general, it's a bit weird how minimal everything is. I think sponsors deserve credit for their support and we should show their logos in a relatively normal way.

So, all of that said, how can we improve OUR sponsor block? I think the main issue is that our sponsors section is super long, right? It takes up a big part of the site right now and I'm sure we'll need to add even more content soon.

Why don't we start with your suggestion of cycling the brands based on levels? That way, the height of the sponsors section will be a lot shorter, and it will be more interesting to watch the different levels cycle through.

Here's how we might accomplish that:

- Split the levels into four sections
- Wrap each section in a .slide div
- Slide 1:
   - Event Sponsors
   - Diamond Level
   - Amazon logo
- Slide 2:
   - Event Sponsors
   - Silver Level
   - Appfolio logo
   - Planning Center logo
- Slide 3:
   - Annual Sponsors
   - Platinum Level
   - LEARN logo
   - Procore logo
- Slide 4:
   - Special Thanks
   - SD Ruby logo
- Remove the horizontal rules from each slide
- Add a top and bottom border to the .slide CSS
- Tweak slide logos to make sure that slides have the same vertical height (so we can use a fixed height for the .slide and there is never too much white space at the bottom of a .slide)
- Use jQuery (or a plugin) to animate the slides (either fading in and out, or sliding in and out)

So that's what I'm thinking. Let me know if that made sense. I'm happy to continue discussing this here, or in Slack, or over Skype if we need to.

**Comment by mokolabs** [comment]
I'm assigning this issue to you, @stephaniejue. It doesn't mean that @sslampa and I won't work on it with you, but you can take the lead since you have issues with the current sponsors block.

👍

**Comment by mokolabs** [comment]
Here's a mockup of how a simplified sponsors section might look:

![demo](https://cloud.githubusercontent.com/assets/444/24470818/1270b6d6-1475-11e7-8350-486312945433.png)

Once the slides are working, we could also experiment with a different layout for each slide.

**Comment by stephchin** [comment]
Totally down for this! Haha I'll work on it later today

**Comment by stephchin** [comment]
- [x] change right/left arrow styling
- [x] change slide durations for each level

**Comment by mokolabs** [comment]
@stephaniejue Can you tweak those arrows? I wanna close out this issue! 😆

**Comment by stephchin** [comment]
Done!

**Comment by mokolabs** [comment]
Sweet. I'm closing this for now!

(Let's make a new issue if we need to tweak anything.)
