### ISSUE TITLE
Update contact form to use AJAX

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#43]
Currently after a message is sent the contact form redirects to the homepage. It would probably look better to just have some sort of success message or notification and not reload the entire page if we can do that.

**Comment by mokolabs** [comment]
Yeah, I was about to add this issue.

So we'll probably need to convert this action to AJAX and then come up with a way to present success and error messages as either popups or inline right next to the submit button.

**Comment by sslampa** [comment]
Because I know you guys don't like my styling here is what I have. I used the given colors that we have, but, obviously, they can be changed.

![selection_007](https://cloud.githubusercontent.com/assets/11300367/24477556/49837890-148c-11e7-8c7f-d6982ef3458f.png)

![selection_008](https://cloud.githubusercontent.com/assets/11300367/24477564/4d5849dc-148c-11e7-8335-205673bde2a1.png)

![selection_009](https://cloud.githubusercontent.com/assets/11300367/24477571/56d1a85a-148c-11e7-91c4-fb16e6233a61.png)

![selection_010](https://cloud.githubusercontent.com/assets/11300367/24477572/5ab5b984-148c-11e7-87b6-63a4c96d6c30.png)

![selection_011](https://cloud.githubusercontent.com/assets/11300367/24477578/5e8d87a8-148c-11e7-82ba-3888f2bc4b81.png)

**Comment by mokolabs** [comment]
Awesome!

**Comment by mokolabs** [comment]
I made a few tweaks. Check 'em out.

@sslampa Can you change the SVG loading icon to white? I think that will match better.

**Comment by sslampa** [comment]
Yup, not a problem

**Comment by mokolabs** [comment]
👍

**Comment by mokolabs** [comment]
I think we're done here. Good job, guys!
