### ISSUE TITLE
Fix timing issue with sponsor slideshow

### ISSUE THREAD

**Issue by stephchin** [railsbridgesd/railsbridgesd#67]
@mokolabs I might have caused this because I changed the interval timing on the slides, but on the first cycle the images load too slow (they load after the text). The 2nd time around its fine. Not sure how to fix.

![screen shot 2017-03-30 at 4 27 55 pm](https://cloud.githubusercontent.com/assets/20118615/24530322/ffeac2ee-1565-11e7-8d12-84427c45f040.png)

**Comment by mokolabs** [comment]
Yeah, it looks like you were setting the interval in two places: once with data attributes in the template and then again using jQuery. These days, I think you just need one, not both.

So I think the weird behavior was because the carousel was trying to use **both** intervals. Sometimes, it would be short. Sometimes, it would be long. That's why.

To fix it, I removed the data attributes and jQuery, and then I added the following jQuery:

```javascript
// Set carousel interval
$('.carousel').carousel({
  interval: 4000
});
```

I went with the same interval for all sponsor slides. Mentally, when you a watch a carousel, it will feel "off" if the timing is different. It goes by too fast for people to think "Oh, this one is less important. I totally get why it had a shorter interval." 😉

With the code above, the carousel is taking exactly 16 seconds. I timed it with my watch!

I'm going to commit these changes.
